spring.application.name=hospital

server.port=8090
server.address=127.0.0.1

# ── PostgreSQL ────────────────────────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitaldb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=hospital_user
spring.datasource.password=hospital_pass

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ── Spring Boot Actuator ──────────────────────────────────────────────────────
management.endpoints.access.default=unrestricted
management.endpoint.health.access=unrestricted
management.endpoint.health.show-details=always
